## Aim of the BM327 Semester 1 Microbiology laboratory sessions

The aim of this block of laboratory sessions is to introduce students to fundamental molecular biology and microbiology methods, such as UV mutagenesis, plasmid transfer, antibiotic assays and microscopy.

Within the block of five three-hour laboratory sessions, there are five distinct experimental elements. Each experimental element is linked to the others as part of an overall research project. Most of the experimental elements will take place over the course of several different laboratory sections (because of the need to incubate plates and allow microbes to grow). There are also two workshops to supplement your learning – details of these will be made available on MyPlace.


## Microbiology Laboratories Competency Skills

Graduate recruiters look for specific job skills and competencies. Competencies are action-oriented statements of the knowledge, skills, and abilities people need to do their work successfully. They are observable and measurable. These are what you need to do the job and work in their organisation. Some are straightforward and required in many different career: communication, teamwork and problem solving are just a few. You need to show employers you have mastered essential skills such as writing, reading, numeracy, presentation, organisation and the ability to work under pressure. Graduates who demonstrate their analytical thinking during a job interview or assessment centre will stand out from other candidates. Other skills such as those gained in the laboratory are more specific and aligned to particular types of jobs e.g. ability to do a PCR.

You will be assessed for your competency in the following:

*Lab 1*
{{< include ./_includes/lab1comp.qmd >}}

*Lab 2*
{{< include ./_includes/lab2comp.qmd >}}

*Lab 3*
{{< include ./_includes/lab3comp.qmd >}}

*Lab 4*
{{< include ./_includes/lab4comp.qmd >}}

*Lab 5*
{{< include ./_includes/lab5comp.qmd >}}

## Overall learning outcomes

*	To understand how exposure to UV radiation can affect the ability of microorganisms to survive and produce antibiotics.

*	To understand how genetic elements are transferred between bacteria.

*	To understand how the susceptibility of bacteria to certain antibiotics is determined.

*	To observe how bacterial cells can change their morphology as a result of certain environmental stimuli.
