---
title: "Experiment 1 Aims and Overview"
---

## Aims 

* To understand how exposure to mutagens can affect the ability of microorganisms to survive and produce antibiotics.

## Learning Outcomes

At the end of this experiment, you should understand:

*	How mutagenesis can affect the phenotype of an organism.

*	That caffeine is a potent mutagen.

*	That mutagens act in a dose-dependent manner.

*	How to analyse a mutagenesis data set.


## Competencies 

{{< include ./_includes/lab1comp.qmd >}}

## Importance

This practical session aligns with lectures in BM330 Fundamental Microbiology and reinforces material relating to: bacterial genetics, mutagenesis, establishing kill kinetics in sterilisation processes, the induction of DNA damage by mutagens in industrial microbiology and strain improvement.

Mutagens like caffeine and UV damage DNA and, at high enough doses, are lethal. Caffeine and UV have long been used as potent, effective mutagens by bacterial geneticists: UV causes the formation of pyrimidine-pyrimidine dimers, and inhibits excision-repair mechanisms for DNA. If left unrepaired pyrimidine-pyrimidine dimers lead to DNA replication errors (mutations). Caffeine and UV are relatively non-site specific mutagens, and can be used to introduce mutations randomly throughout a genome. These mutations may cause different phenotypic changes in the bacteria being studied, depending on the location and nature of the mutation.


## Overview of Experiment 1

You will perform Protocol 1.1 in the Week 2 lab and collect your data the following session (Week 4). Perform the data analysis tasks (@sec-data1) using your own data/the class data or the sample data available on MyPlace.

::: {.todo title="To prepare for Lab 1"}

Before attending the practical lab, you should ensure that you have read and understood:

* The introductory sections covering [Good Lab Practice](./0goodlab.qmd) and [Aseptic Technique](./0aseptic.qmd)

* The introductory sections covering the [aim and rationale underpinning this experiment](./1intro1.qmd), the theory on [Streptomyces and Antibiotic Production](./1intro2.qmd), and [Bacterial Mutagenesis](./1intro3.qmd) 

* The [Protocols](./1protocols.qmd) we will be following in the lab

You also must ensure that you have read and signed the safety forms, or you will not be admitted to the lab.

:::