---
title: Experiment 1 - Data Analysis
---

::: {.todo title="Experiment 1 - Data Analysis Tasks"}

After completing all of the practical lab tasks for this experiment, you should analyse (@sec-1Adata and @sec-1Bdata):

* The caffeine mutagenesis experiment (your data/class data on MyPlace)

*	The UV mutagenesis data (experiment performed for you and data posted on MyPlace)

:::

## Task 1A {#sec-1Adata}

1. You will be provided with a set of data from the UV mutagenesis experiment (available on MyPlace). 

The data shows you three plates for each time point, starting at T=0 (un-irradiated spores) and then the number of colonies present on the plates after the time indicated, and the dilution of the spores to obtain that count. The times are T = 0 (un-irradiated spores); 30 seconds (0.5 min) UV treatment; 1 min UV treatment; 2 min UV treatment; 4 min UV treatment; 8 min UV treatment and 16 UV treatment. Each plate contains 1 ml of spores.

2. You should make the following calculations: 
a.	Using the triplicate counts for each time point, work out the mean CFU survival following UV irradiation or caffeine treatment of the spores for each time point.

b.	Using these data plot a UV dose versus survival graph of your data (x-axis = time; y-axis = CFU/ml).

Using the data, work out the percentage survival of spores following irradiation or caffeine treatment. Establish the time-point that gives >99% spore killing. (x-axis = time; y-axis = percentage spore survival). Un-irradiated spores will be 100%



### Task 1B - Analyse mutant phenotypes {#sec-1Bdata}

1.	Compare the colonies obtained on the irradiated plates with those on the equivalent dilutions of unirradiated plates (data available on MyPlace). 

2.	Carefully record your data (observations) in an appropriate format.

3.	Can you identify over-producing mutants of the pigmented antibiotic Actinorhodin (Blue) or undecylprodigiosin (Red)? Do the colonies look different after UV mutagenesis?

4.	We have already selected a number of mutants for further analysis – but which mutants would you have selected (and why)?

::: {.callout-discussion title="Experiment 1 - discussion questions"} 

* Compare the two mutagens we used (UV and caffeine). Which is more effective in terms of killing (@sec-1Adata)? in terms of generating mutants with the desired phenotypes (@sec-1Bdata)?

* Which colonies would you select for further analysis?

* What experiments would you like to do to characterize these mutant strains?

* What are the advantages and disadvantages of using UV mutagenesis? Caffeine mutagenesis?

:::