---
 title: "Experiment 1 - Background"
 format: html
---

## Experiment 1 - Background {#sec-intro1}

We have isolated a mutant strain of <i>Streptomyces coelicolor</i> A3(2) that produces a novel antibiotic that can kill <i>Escherichia coli</i> and other Gram-negative bacteria. However, the <i>Streptomyces</i> strain only produces small amounts of the antibiotic.

In order to study this antibiotic further, you will carry out a UV mutagenesis experiment, and screen for mutants that produce more antibiotic (@sec-protocols1).

Your task is to determine the most effective dose of UV radiation to use for isolating mutants (@sec-1Adata). You will then analyse the phenotypes of mutants isolated at this dose (@sec-1Bdata). 

We have selected a number of candidate genes that might be involved in regulating antibiotic production, and sequenced these genes in a set of mutant strains. Your final task for this experiment is to examine the potentially mutant allele sequences, and identify any amino acid change(s) compared to the wild-type sequence (Workshop 1).