---
title: "Experiment 3 Aims and Overview"
---

## Aims 

* To understand how genetic elements are transferred between bacteria.

## Learning Outcomes

At the end of this laboratory session, you should understand:

*	That horizontal gene transfer (HGT) can occur between two strains of bacteria

*	That HGT can affect the phenotype of an organism

*	That plasmid transfer occurs in a specific order 

*	How to analyse the results of a conjugative transfer experiment



## Competencies 

{{< include ./_includes/lab3comp.qmd >}}

## Importance

This practical session aligns with lectures in BM330 Fundamental Microbiology and reinforces material relating to: horizontal gene transfer, bacterial genetics. 

## Isolation of a new antibiotic from *Streptomyces coelicolor*: Mapping mutations that confer antibiotic resistance

You have isolated a strain of *Streptomyces coelicolor* A3(2) that produces a novel antibiotic that can kill *Escherichia coli* and other Gram-negative bacteria. In the previous lab, you isolated *E. coli* strains that are resistant to this particular antibiotic.

In order to identify the mutation(s) that give rise to the antibiotic resistance phenotype, you will physically map the location of the mutations using interrupted mating. You will first analyse the data from the interrupted mating experiment (@sec-task3A), and then form a hypothesis about the location of the antibiotic-resistance mutation (@sec-task3B). 




## Overview of Experiment 3

You will perform Protocol 3.1 in the Week 6 lab and collect your data the following session (Week 8). Perform the data analysis tasks (@sec-data3) using your own data/the class data or the sample data available on MyPlace.
