---
title: Experiment 4 - Data Analysis
---

# Experiment 4 - Data Analysis {#sec-data4}

You have 2 sets of data to analyse for Experiment 4:

*	The images of the agarose gels you ran in the lab (available for you on MyPlace) - You will use these data in @sec-task4A.

*	Sequence data from these plasmids (available for you on MyPlace) - You will use these data in workshop 3.

## TASK 4A. Plasmid rescue {#sec-task4A}

1.	The data from the lab (your agarose gel pictures) will be made available for you on MyPlace. Download the image of your gel, and label the lanes correctly.

2.	Use the DNA ladder to estimate the size of the bands from your restriction digests (either by eye, or by using the DNA ladder to generate a standard curve of DNA size vs. distance migrated).

3.	Draw a map of the plasmid, including all known restriction sites and any other pertinent information (such as the location of the Tn*5*), keeping in mind that the plasmid is circular.

::: {.callout-tip title="Top tips for restriction mapping of a plasmid" collapse="true"}

* Think logically - e.g., if a circular piece of DNA is cut once, how many bands will it produce? What if it is cut twice?

* Keep the limits of agarose gel electrophoresis in mind - e.g., it may be difficult to precisely estimate band sizes in some cases, and/or you might have two or more bands that don't resolve well (depending on your experiment and electrophoresis conditions)

* Check out a [worked example to see how someone else performs this task](https://www.youtube.com/watch?v=uNvF9ZBufTk)

:::



::: {.callout-discussion title="Experiment 4 Discussion Questions"} 

* We used plasmid rescue followed by sequencing to identify the location of the Tn*5* insertions in your mutant *E. coli* strains (these Tn insertions are presumably responsible for making the strains resistant to your novel antibiotic). How well did this technique do at mapping the location of the transposons? How effective was it compared to the mapping experiment you performed (Experiment 3)?

* Are there any other techniques or methods you could use to identify the Tn location (instead of plasmid rescue and sequencing)?

* What conclusions can you draw based upon the experiments performed in this lab?

* What further experiments might you do (and why?)

:::
