---
 title: "Experiment 4 - Background"
 format: html
---

## Experiment 4 - Background {#sec-bkgd4}

A fundamental difficulty in biology lies in our ability to link genotype and phenotype: for example, as in this experiment where we will try to link the known phenotype (antibiotic resistance) with the unknown mutation causing the phenotype (location of the Tn*5* insertion).

In this lab we will be performing a “plasmid rescue” experiment to “rescue” the Tn*5* inserted into the chromosome of the mutant strains. This technique uses restriction enzymes that randomly cut chromosomal DNA isolated from the mutant bacteria; this is then ligated into a vector, and *E. coli* DH5α cells are transformed with this ligation mixture. Transformed cells which carry the region of the chromosome carrying the Tn*5* insertion, will be resistant to tetracycline. The plasmid containing this DNA is isolated from the transformants and Sanger sequencing used to identify the exact position of the Tn5 insertion.

Restriction enzymes are invaluable tools in molecular microbiology. These enzymes make site-specific cuts in DNA (at positions termed restriction sites), and are a key part of the innate immune defences that bacteria use to protect themselves against incoming foreign DNA. Restriction enzymes have found a multitude of applications in molecular biology labs, including their use in cloning, digestion of DNA for Southern blotting, identification of nucleotide differences using restriction fragment length polymorphism (RFLP) analysis, etc. Being able to carry out a restriction digest of DNA, and analyse the results, is therefore a key skill for any microbiologist or molecular biologist.


